#!/bin/sh 

mount -t proc none /proc 
mount -t sysfs none /sys 
mount -t devtmpfs none /dev 

echo 
echo "Tiny embedded Linux has booted" 
echo 

/usr/local/bin/sensor-stats 12 15 18 21

exec /bin/sh 
EOF
